### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SanjeebLama** [IshaqKassam/Reactjs-Blogging-System#1]
Hi, I'm new to react.
I was studying your code.
I cloned and tried in my own firebase.
However, the problem is I cannot create a new admin or access ADMIN panel.

Can you give some hints or redirect me to some tutorial. It would be really helpful.
Thanks.

**Comment by IshaqKassam** [comment]
Hi Sanjeeb, 

Thanks for this, 

For the deployed version, there's a master admin, and users can be added as admin by the master admin.

For your case, as a workaround, you can manually add a user under the 'admin' node in the firebase real-time database.

Feel free to reach out if anything - ishaq.kassam@gmail.com
